package com;

/**
 * Oriented rigid box with impulse based contact physics.
 *
 * Direct J2ME style port of the OBB solver from portalDS
 * (arm7/source/OBB.c + arm7/source/AAR.c), adapted to this engine:
 *
 *  - all state is Q12 fixed point (4096 == 1.0): no floating point and no
 *    per frame allocations anywhere in the solver,
 *  - semi-implicit Euler integration with a first order rotation update
 *    followed by a Gram-Schmidt matrix re-orthonormalization,
 *  - contacts are generated by a full separating axis test (SAT) of the
 *    box against every nearby triangle/quad of the engine's meshes: the
 *    3 box face axes, the polygon face axis and the 3 x N edge cross
 *    axes; the axis of minimum penetration becomes the reference feature
 *    and feeds a clipped reference-face/incident-face manifold (the
 *    classic box2d-lite scheme). This replaces the old per-vertex point
 *    scans, which could only approximate box-vs-triangle penetrations
 *    and spun the box about the wrong axis at convex corners,
 *  - sequential contact impulses with restitution and Coulomb friction,
 *  - adaptive substeps: the integrated state is backed up and the step is
 *    halved whenever a contact penetrates too deep,
 *  - the body falls asleep once it rests on an upward facing surface.
 *
 * World coordinates are plain engine units (one solver step per rendered
 * frame). Mesh face normals follow the SphereCast convention and point INTO
 * the solid, so an outward contact normal is the negated mesh normal. The
 * geometry is treated as one-sided sheets: a separating push generated
 * against a polygon never points into that polygon's solid side, exactly
 * like the old vertex code which always used -meshNormal for face contacts.
 *
 * Matrices are 3x3 row-major Q12; orientation matrix R maps local vectors
 * to world vectors (world = R * local).
 */
public final class RigidBody {

	/** Q12 scale. */
	public static final int F = 4096;

	// ===================== contact generation tuning =====================

	/** Upper bound on simultaneous contacts feeding the solver. */
	private static final int MAX_CONTACTS = 32;
	private static final int VERTICES = 8;

	/** A polygon counts as hit while its minimum axis separation is deeper
	 *  than -this; anything below is cleanly separated. This matches the
	 *  old vertex code's SURFACE_TOUCH band: resting happens within a few
	 *  units of the surface instead of hovering on speculative impulses,
	 *  while the substep rollback absorbs the first real impact. Units. */
	private static final int SAT_AXIS_MARGIN = 6;
	/** A manifold point up to this far on the free side of the reference
	 *  plane still counts as touching (units, like the old SURFACE_TOUCH):
	 *  the resting contact lives in this band instead of requiring real
	 *  overlap every frame. */
	private static final int SAT_TOUCH_TOL = 6;
	/** Edge (cross product) axes must beat the best face axis by this much
	 *  to become the reference feature. Face manifolds are far more stable
	 *  frame to frame than single point edge manifolds; letting a nearly
	 *  tied edge axis win makes the contact point hop between face and edge
	 *  every frame, which shows up as rotational jitter. Units. */
	private static final int SAT_CROSS_BIAS = 2;
	/** Cross axes from near-parallel box-axis/polygon-edge pairs are
	 *  skipped: their normalized direction is pure rounding noise. Test is
	 *  |cross| * this <= |edge| (i.e. sin(angle) < 1/this). */
	private static final int SAT_PARALLEL_SHIFT = 100;
	/** An axis is treated as tangential to the current polygon's solid side
	 *  when |axis . outwardNormal| falls below this (Q12): only then may
	 *  the escape pick its cheaper side, otherwise the push direction is
	 *  fixed by the outward normal (the mesh is one-sided sheets). */
	private static final int SAT_TANGENTIAL = 32;
	/** Max manifold points kept per polygon (deepest first, then the
	 *  farthest spread so the torque from the manifold stays honest). */
	private static final int MAX_MANIFOLD_POINTS = 4;
	/** Contacts with matching normals closer than this are the same contact
	 *  (squared, Q12): wall/floor seam duplicates that adjacent coplanar
	 *  polygons produce get merged instead of applying double impulses at
	 *  one spot (which snaps the box every frame). */
	private static final int MERGE_NORMAL_DOT = F - F / 64;
	private static final long MERGE_DIST2 = (long) (8 << 12) * (8 << 12);

	// reference feature types (sat best axis classification)
	private static final int FEATURE_POLY_FACE = 0;
	private static final int FEATURE_BOX_FACE = 1;
	private static final int FEATURE_EDGE = 2;

	/** Contacts are generated against polygons inside this band around the
	 *  box (broadphase only, units). */
	private static final int CONTACT_MARGIN = 64;
	/** Deeper penetration than this rolls the step back and halves dt. */
	private static final int PENETRATION_THRESHOLD = 64;
	/** Smallest substep as a fraction of a frame (1/256). */
	private static final int MIN_DT = 16;
	/** Gauss-Seidel sweeps over the contact list per frame. */
	private static final int IMPULSE_ITERATIONS = 8;
	/** Position projection sweeps; every contact is de-penetrated, not just
	 *  the deepest one, so a cube wedged in a corner cannot be repeatedly
	 *  snapped and gain energy. */
	private static final int POSITION_ITERATIONS = 4;
	/** Contacts within this many units are treated as resting (no projection). */
	private static final int POSITION_SLOP = 3;
	/** Hard safety clamps: pathological single-vertex corner contacts must
	 *  never launch or spin the cube beyond gameplay-scale velocities. */
	private static final int MAX_LINEAR = 2048 << 12;
	private static final int MAX_ANGULAR = 2 * F;
	/** Impacts slower than this (Q12 units/frame) are treated as inelastic,
	 *  otherwise micro rocking on a resting contact never damps out. */
	private static final int RESTITUTION_SPEED = 30 << 12;

	/** Gravity, units per frame (matches Character: speed.y -= 20). */
	private static final int GRAVITY = 20 << 12;
	/** Linear velocity damping divisor (v -= v / 25 per frame). */
	private static final int LINEAR_DRAG = 25;
	/** Angular velocity damping divisor. */
	private static final int ANGULAR_DRAG = 20;

	/** Contact material against world geometry (portalDS plane values). */
	private static final int RESTITUTION = 819;   // 0.2
	private static final int FRICTION = 4096;    // 1.0

	// Sleep thresholds are energy values (Q12 of units/frame, squared).
	private static final int SLEEP_LOW = 120000;
	private static final int SLEEP_HIGH = 400000;
	private static final int SLEEP_TIME = 16;

	// ---- body state (all Q12 unless noted) ----
	private int hx, hy, hz;          // half extents
	private int mass, invMass;
	private int il0, il4, il8;       // local inertia (inverse of invILocal)
	private int px, py, pz;          // center position
	private int vx, vy, vz;          // linear velocity, units/frame
	private int lx, ly, lz;          // angular momentum
	private int wx, wy, wz;          // angular velocity
	private final int[] r = new int[9];   // orientation, row-major
	private final int[] invILocal = new int[9];
	private final int[] invIWorld = new int[9];

	// ---- contacts ----
	private final int[] cpx = new int[MAX_CONTACTS];
	private final int[] cpy = new int[MAX_CONTACTS];
	private final int[] cpz = new int[MAX_CONTACTS];
	private final int[] cnx = new int[MAX_CONTACTS];
	private final int[] cny = new int[MAX_CONTACTS];
	private final int[] cnz = new int[MAX_CONTACTS];
	private final int[] cpen = new int[MAX_CONTACTS];
	private int numContacts;
	private int maxPenetration;
	private boolean groundContact;

	// ---- SAT scratch (no per frame allocation) ----
	/** Current polygon, world space, engine units: up to 4 verts * xyz. */
	private final int[] polyPts = new int[12];
	private int polyCount;
	/** Outward (out of the solid) unit normal of the current polygon, Q12. */
	private int polyNX, polyNY, polyNZ;
	/** Double buffer for the clipping loops: up to 8 verts * xyz. */
	private int[] clipA = new int[24];
	private int[] clipB = new int[24];
	private final int[] sdBuf = new int[8];
	private final int[] selIdx = new int[MAX_MANIFOLD_POINTS];
	private final int[] selTmp = new int[MAX_MANIFOLD_POINTS * 3];
	private final int[] selSdTmp = new int[MAX_MANIFOLD_POINTS];
	private final int[] colBuf = new int[3];

	/** Separation of the last axisSeparation call (units; < 0 == gap). */
	private int satSep;
	private int satDirX, satDirY, satDirZ;
	/** Best (deepest) axis over the whole SAT: reference feature. */
	private int bestSep;
	private int bestDX, bestDY, bestDZ;
	private int bestType, bestI, bestJ;

	/** Closest points between two segments, result of segmentClosest (units). */
	private int segPx, segPy, segPz, segQx, segQy, segQz;

	// ---- world AABB (units) ----
	private int boxMinX, boxMinY, boxMinZ, boxMaxX, boxMaxY, boxMaxZ;
	private int cornerRadius;

	// ---- backup for substep rollback ----
	private int bpx, bpy, bpz, bvx, bvy, bvz, blx, bly, blz, bwx, bwy, bwz;
	private final int[] br = new int[9];
	private final int[] biw = new int[9];

	private boolean sleeping;
	private int sleepCounter;
	private int energy;
	/** Number of integration substeps used by the last frame (for tests). */
	public int lastSubsteps = 1;

	/**
	 * Triangle/quad mesh as the engine stores it (see MeshData and
	 * SphereCast): short indexed vertices/polygons, Q12 polygon normals and
	 * an fp8 scale with integer offsets applied to every vertex.
	 */
	public static final class Collider {
		public short[] verts;
		public short[] pols;
		public short[] norms;
		public int quads;
		public int tris;
		public int scale8;
		public int offX, offY, offZ;
	}

	public RigidBody(int halfExtentUnits) {
		this.hx = this.hy = this.hz = halfExtentUnits << 12;
		reset(0, 0, 0);
	}

	/** Mass is 1.0 Q12 by default; heavier bodies move less eagerly. */
	public void setMass(int massQ12) {
		this.mass = massQ12;
		this.invMass = divQ(F, massQ12);
		computeLocalInertia();
	}

	/** Places the body at a center position given in engine units. */
	public void reset(int centerX, int centerY, int centerZ) {
		this.mass = F;
		this.invMass = F;
		this.px = centerX << 12;
		this.py = centerY << 12;
		this.pz = centerZ << 12;
		this.vx = this.vy = this.vz = 0;
		this.lx = this.ly = this.lz = 0;
		this.wx = this.wy = this.wz = 0;
		for(int i = 0; i < 9; i++) r[i] = 0;
		r[0] = r[4] = r[8] = F;
		computeLocalInertia();
		recomputeWorldInertia();
		this.sleeping = false;
		this.sleepCounter = 0;
		this.energy = 0;
		computeVertices();
	}

	public void wake() {
		this.sleeping = false;
		this.sleepCounter = 0;
	}

	public boolean isSleeping() {
		return sleeping;
	}

	/** Number of contacts generated for the last solved frame. */
	public int getContactCount() {
		return numContacts;
	}

	// ---- accessors (engine units) ----

	public int getCenterX() { return px >> 12; }
	public int getCenterY() { return py >> 12; }
	public int getCenterZ() { return pz >> 12; }

	public int getVelocityX() { return vx >> 12; }
	public int getVelocityY() { return vy >> 12; }
	public int getVelocityZ() { return vz >> 12; }

	public int getHalfExtent() { return hx >> 12; }

	/** Orientation entry, row-major (0..8), Q12. */
	public int getOrientation(int i) { return r[i]; }

	public void setVelocity(int unitsX, int unitsY, int unitsZ) {
		this.vx = unitsX << 12;
		this.vy = unitsY << 12;
		this.vz = unitsZ << 12;
		wake();
	}

	public int getAngularX() { return wx; }
	public int getAngularY() { return wy; }
	public int getAngularZ() { return wz; }

	/** Sets angular velocity (Q12 radians/frame) and derives momentum from it. */
	public void setAngularVelocity(int ax, int ay, int az) {
		this.wx = ax; this.wy = ay; this.wz = az;
		recomputeMomentum();
		wake();
	}

	/** Instant positional nudge (used for kinematic character pushes). */
	public void nudge(int dxUnits, int dyUnits, int dzUnits) {
		this.px += dxUnits << 12;
		this.py += dyUnits << 12;
		this.pz += dzUnits << 12;
		// a push also becomes velocity, otherwise the cube would not slide
		this.vx += dxUnits << 12;
		this.vy += dyUnits << 12;
		this.vz += dzUnits << 12;
		wake();
	}

	/**
	 * Kinematic placement while held: follows a target center point and
	 * keeps an axis aligned orientation. The frame to frame delta becomes
	 * the body velocity so a throw inherits the carry motion.
	 */
	public void moveKinematic(int centerX, int centerY, int centerZ) {
		int nx = centerX << 12, ny = centerY << 12, nz = centerZ << 12;
		this.vx = nx - px;
		this.vy = ny - py;
		this.vz = nz - pz;
		this.px = nx;
		this.py = ny;
		this.pz = nz;
		this.lx = this.ly = this.lz = 0;
		this.wx = this.wy = this.wz = 0;
		identity3(r);
		recomputeWorldInertia();
		wake();
		computeVertices();
	}

	/**
	 * Applies a portal warp matrix (row-major float[16], as produced by
	 * PortalManager.getPortalTransform) to position, velocities and the
	 * orientation frame.
	 */
	public void warp(float[] m) {
		float x = px / (float) F, y = py / (float) F, z = pz / (float) F;
		px = q(m[0] * x + m[1] * y + m[2] * z + m[3]);
		py = q(m[4] * x + m[5] * y + m[6] * z + m[7]);
		pz = q(m[8] * x + m[9] * y + m[10] * z + m[11]);

		int[] wv = warpVector(m, vx, vy, vz);
		vx = wv[0]; vy = wv[1]; vz = wv[2];
		wv = warpVector(m, wx, wy, wz);
		wx = wv[0]; wy = wv[1]; wz = wv[2];

		// Rotate the three orientation columns (axes).
		for(int col = 0; col < 3; col++) {
			float ax = r[col] / (float) F;
			float ay = r[3 + col] / (float) F;
			float az = r[6 + col] / (float) F;
			r[col] = q(m[0] * ax + m[1] * ay + m[2] * az);
			r[3 + col] = q(m[4] * ax + m[5] * ay + m[6] * az);
			r[6 + col] = q(m[8] * ax + m[9] * ay + m[10] * az);
		}
		fixMatrix();
		recomputeWorldInertia();

		// angular momentum consistent with the rotated angular velocity
		recomputeMomentum();
		wake();
		computeVertices();
	}

	private final int[] warpScratch = new int[3];
	private int[] warpVector(float[] m, int x, int y, int z) {
		float fx = x / (float) F, fy = y / (float) F, fz = z / (float) F;
		warpScratch[0] = q(m[0] * fx + m[1] * fy + m[2] * fz);
		warpScratch[1] = q(m[4] * fx + m[5] * fy + m[6] * fz);
		warpScratch[2] = q(m[8] * fx + m[9] * fy + m[10] * fz);
		return warpScratch;
	}
	private static int q(float v) {
		return (int) (v * F);
	}

	// ===================== simulation =====================

	/**
	 * Advances the body by one frame.
	 *
	 * @param colliders meshes of the current and neighbouring rooms
	 * @param count     number of valid entries
	 * @param world     test world collisions (false while crossing a portal
	 *                  opening)
	 */
	public void step(Collider[] colliders, int count, boolean world) {
		if(sleeping) {
			vx = vy = vz = 0;
			wx = wy = wz = 0;
			lx = ly = lz = 0;
			computeVertices();
			this.energy = 0;
			return;
		}

		// Gravity plus portalDS style velocity damping, expressed as forces.
		int fx = -vx / LINEAR_DRAG;
		int fy = -GRAVITY - vy / LINEAR_DRAG;
		int fz = -vz / LINEAR_DRAG;
		int mx = -wx / ANGULAR_DRAG;
		int my = -wy / ANGULAR_DRAG;
		int mz = -wz / ANGULAR_DRAG;

		int dt = F;
		int substeps = 1;
		while(true) {
			backup();
			integrate(dt, fx, fy, fz, mx, my, mz);
			collideWorld(colliders, count, world);

			if(maxPenetration > PENETRATION_THRESHOLD << 12 && dt > MIN_DT) {
				restore();
				dt >>= 1;
				++substeps;
				continue;
			}

			if(numContacts > 0) applyImpulses();
			break;
		}
		this.lastSubsteps = substeps;

		// Safety clamps run on every frame (not only contact frames): a
		// pathological impact must never leave a runaway spin behind.
		clampVelocity();

		// Sleep bookkeeping: only a body supported from below may rest.
		energy = mul(vx, vx) + mul(vy, vy) + mul(vz, vz)
				+ mul(wx, wx) + mul(wy, wy) + mul(wz, wz);
		if(!groundContact) {
			sleepCounter = 0;
		} else if(energy >= SLEEP_HIGH) {
			sleeping = false;
			sleepCounter = 0;
		} else if(energy <= SLEEP_LOW) {
			if(++sleepCounter >= SLEEP_TIME) {
				sleeping = true;
				vx = vy = vz = 0;
				wx = wy = wz = 0;
				lx = ly = lz = 0;
			}

		} else {
			sleepCounter = 0;
		}

		computeVertices();
	}

	private void integrate(int dt, int fx, int fy, int fz, int mx, int my, int mz) {
		// position += v * dt
		px += mul(vx, dt);
		py += mul(vy, dt);
		pz += mul(vz, dt);

		// R += skew(w * dt) * R, first order rotation update
		int wxd = mul(wx, dt), wyd = mul(wy, dt), wzd = mul(wz, dt);
		for(int row = 0; row < 3; row++) {
			int s0, s1, s2;
			if(row == 0) { s0 = 0; s1 = -wzd; s2 = wyd; }
			else if(row == 1) { s0 = wzd; s1 = 0; s2 = -wxd; }
			else { s0 = -wyd; s1 = wxd; s2 = 0; }
			for(int col = 0; col < 3; col++) {
				int v = mul(s0, r[col]) + mul(s1, r[3 + col]) + mul(s2, r[6 + col]);
				r[row * 3 + col] += v;
			}
		}

		// v += f * dt / mass
		vx += divQ(mul(fx, dt), mass);
		vy += divQ(mul(fy, dt), mass);
		vz += divQ(mul(fz, dt), mass);

		// L += moment * dt
		lx += mul(mx, dt);
		ly += mul(my, dt);
		lz += mul(mz, dt);

		fixMatrix();
		recomputeWorldInertia();
		wx = eval24X(invIWorld, lx, ly, lz);
		wy = eval24Y(invIWorld, lx, ly, lz);
		wz = eval24Z(invIWorld, lx, ly, lz);
	}

	/**
	 * Local inertia of a box with half extents h: I = m/3(h2+h3).
	 * The inverse tensor is stored in Q24 because at world cube scale (half
	 * extent ~500 units) its Q12 value is below the fixed point resolution;
	 * the positive tensor used for angular momentum stays Q12.
	 */
	private void computeLocalInertia() {
		identity3(invILocal);
		int x2 = mul(hx, hx), y2 = mul(hy, hy), z2 = mul(hz, hz);
		invILocal[0] = (int) (((long) (3 * F) << 24) / mul(mass, y2 + z2));
		invILocal[4] = (int) (((long) (3 * F) << 24) / mul(mass, x2 + z2));
		invILocal[8] = (int) (((long) (3 * F) << 24) / mul(mass, x2 + y2));
		il0 = mul(mass, y2 + z2) / 3;
		il4 = mul(mass, x2 + z2) / 3;
		il8 = mul(mass, x2 + y2) / 3;
	}

	/** invIWorld (Q24) = R * invILocal * R^T */
	private void recomputeWorldInertia() {
		for(int row = 0; row < 3; row++) {
			for(int col = 0; col < 3; col++) {
				int t0 = mul(r[row * 3], invILocal[0]);
				int t1 = mul(r[row * 3 + 1], invILocal[4]);
				int t2 = mul(r[row * 3 + 2], invILocal[8]);
				int v = mul(t0, r[col * 3]) + mul(t1, r[col * 3 + 1]) + mul(t2, r[col * 3 + 2]);
				invIWorld[row * 3 + col] = v;
			}
		}
	}

	/** Evaluates a Q24 3x3 matrix against a Q12 vector, result Q12. */
	private static int eval24X(int[] m, int x, int y, int z) {
		return (int) (((long) m[0] * x + (long) m[1] * y + (long) m[2] * z) >> 24);
	}
	private static int eval24Y(int[] m, int x, int y, int z) {
		return (int) (((long) m[3] * x + (long) m[4] * y + (long) m[5] * z) >> 24);
	}
	private static int eval24Z(int[] m, int x, int y, int z) {
		return (int) (((long) m[6] * x + (long) m[7] * y + (long) m[8] * z) >> 24);
	}

	/** L = Iworld (Q12, built from il0..il8) * w */
	private void recomputeMomentum() {
		int[] iw = tmpMatrix;
		for(int row = 0; row < 3; row++) {
			for(int col = 0; col < 3; col++) {
				int t0 = mul(r[row * 3], il0);
				int t1 = mul(r[row * 3 + 1], il4);
				int t2 = mul(r[row * 3 + 2], il8);
				iw[row * 3 + col] = mul(t0, r[col * 3]) + mul(t1, r[col * 3 + 1]) + mul(t2, r[col * 3 + 2]);
			}
		}
		lx = evalX(iw, wx, wy, wz);
		ly = evalY(iw, wx, wy, wz);
		lz = evalZ(iw, wx, wy, wz);
	}

	/** Gram-Schmidt re-orthonormalization of the three axis columns. */
	private void fixMatrix() {
		int xx = r[0], xy = r[3], xz = r[6];
		int yx = r[1], yy = r[4], yz = r[7];

		// Stable Gram-Schmidt: normalize the x column, project the y column
		// onto it, then rebuild z as x cross y. The cross product makes the
		// frame exact even when the first order rotation update has driven
		// two raw columns nearly parallel (large per-frame spins after a
		// corner impact), where the old three-projection form degenerated.
		int mx = norm3(xx, xy, xz);
		if(mx == 0) { identity3(r); return; }
		xx = divQ(xx, mx); xy = divQ(xy, mx); xz = divQ(xz, mx);

		int d = mul(xx, yx) + mul(xy, yy) + mul(xz, yz);
		yx -= mul(xx, d); yy -= mul(xy, d); yz -= mul(xz, d);
		int my = norm3(yx, yy, yz);
		if(my == 0) { identity3(r); return; }
		yx = divQ(yx, my); yy = divQ(yy, my); yz = divQ(yz, my);

		// z = x cross y (columns are x=(r0,r3,r6), y=(r1,r4,r7))
		int zx = mul(xy, yz) - mul(xz, yy);
		int zy = mul(xz, yx) - mul(xx, yz);
		int zz = mul(xx, yy) - mul(xy, yx);

		r[0] = xx; r[3] = xy; r[6] = xz;
		r[1] = yx; r[4] = yy; r[7] = yz;
		r[2] = zx; r[5] = zy; r[8] = zz;
	}

	// ===================== contact generation (SAT) =====================

	private void collideWorld(Collider[] colliders, int count, boolean world) {
		numContacts = 0;
		maxPenetration = 0;
		groundContact = false;
		computeVertices();
		if(!world) return;

		// Broadphase is swept against the pre-integration position: after a
		// deep (to be rolled back) step the box may sit beyond the very
		// surface it should collide with and would otherwise cull it.
		int bcr = cornerRadius + CONTACT_MARGIN;
		int bX = bpx >> 12, bY = bpy >> 12, bZ = bpz >> 12;
		int bandMinX = Math.min(boxMinX, bX - bcr) - CONTACT_MARGIN;
		int bandMinY = Math.min(boxMinY, bY - bcr) - CONTACT_MARGIN;
		int bandMinZ = Math.min(boxMinZ, bZ - bcr) - CONTACT_MARGIN;
		int bandMaxX = Math.max(boxMaxX, bX + bcr) + CONTACT_MARGIN;
		int bandMaxY = Math.max(boxMaxY, bY + bcr) + CONTACT_MARGIN;
		int bandMaxZ = Math.max(boxMaxZ, bZ + bcr) + CONTACT_MARGIN;

		for(int ci = 0; ci < count; ci++) {
			Collider mesh = colliders[ci];
			short[] verts = mesh.verts;
			short[] pols = mesh.pols;
			short[] norms = mesh.norms;
			int s8 = mesh.scale8;
			int ox = mesh.offX, oy = mesh.offY, oz = mesh.offZ;

			int x1 = ((bandMinX - ox) << 8) / s8 - 1;
			int y1 = ((bandMinY - oy) << 8) / s8 - 1;
			int z1 = ((bandMinZ - oz) << 8) / s8 - 1;
			int x2 = ((bandMaxX - ox) << 8) / s8 + 1;
			int y2 = ((bandMaxY - oy) << 8) / s8 + 1;
			int z2 = ((bandMaxZ - oz) << 8) / s8 + 1;

			for(int vpp = 4, pIdx = 0, nIdx = 0; vpp >= 3; vpp--) {
				int pEnd = vpp == 4 ? mesh.quads * 4 : pols.length;
				for(; pIdx < pEnd; pIdx += vpp, nIdx++) {
					int i1 = pols[pIdx] * 3, i2 = pols[pIdx + 1] * 3, i3 = pols[pIdx + 2] * 3;
					int sax = verts[i1], say = verts[i1 + 1], saz = verts[i1 + 2];
					int sbx = verts[i2], sby = verts[i2 + 1], sbz = verts[i2 + 2];
					int scx = verts[i3], scy = verts[i3 + 1], scz = verts[i3 + 2];

					int mnx = sax, mxx = sax, mny = say, mxy = say, mnz = saz, mxz = saz;
					if(sbx < mnx) mnx = sbx; if(sbx > mxx) mxx = sbx;
					if(sby < mny) mny = sby; if(sby > mxy) mxy = sby;
					if(sbz < mnz) mnz = sbz; if(sbz > mxz) mxz = sbz;
					if(scx < mnx) mnx = scx; if(scx > mxx) mxx = scx;
					if(scy < mny) mny = scy; if(scy > mxy) mxy = scy;
					if(scz < mnz) mnz = scz; if(scz > mxz) mxz = scz;
					int sdx = 0, sdy = 0, sdz = 0;
					if(vpp == 4) {
						int i4 = pols[pIdx + 3] * 3;
						sdx = verts[i4]; sdy = verts[i4 + 1]; sdz = verts[i4 + 2];
						if(sdx < mnx) mnx = sdx; if(sdx > mxx) mxx = sdx;
						if(sdy < mny) mny = sdy; if(sdy > mxy) mxy = sdy;
						if(sdz < mnz) mnz = sdz; if(sdz > mxz) mxz = sdz;
					}
					if(mxx < x1 || mnx > x2 || mxy < y1 || mny > y2 || mxz < z1 || mnz > z2) continue;

					// world space polygon (engine units) into the SAT scratch
					polyCount = vpp;
					polyPts[0] = (sax * s8 >> 8) + ox;
					polyPts[1] = (say * s8 >> 8) + oy;
					polyPts[2] = (saz * s8 >> 8) + oz;
					polyPts[3] = (sbx * s8 >> 8) + ox;
					polyPts[4] = (sby * s8 >> 8) + oy;
					polyPts[5] = (sbz * s8 >> 8) + oz;
					polyPts[6] = (scx * s8 >> 8) + ox;
					polyPts[7] = (scy * s8 >> 8) + oy;
					polyPts[8] = (scz * s8 >> 8) + oz;
					if(vpp == 4) {
						int i4 = pols[pIdx + 3] * 3;
						polyPts[9] = (verts[i4] * s8 >> 8) + ox;
						polyPts[10] = (verts[i4 + 1] * s8 >> 8) + oy;
						polyPts[11] = (verts[i4 + 2] * s8 >> 8) + oz;
					}

					int snx = norms[nIdx * 3], sny = norms[nIdx * 3 + 1], snz = norms[nIdx * 3 + 2];
					if(snx == 0 && sny == 0 && snz == 0) continue;
					collidePolygon(snx, sny, snz);
				}
			}
		}
	}

	/**
	 * Full SAT of the box against one polygon (triangle or quad), followed
	 * by manifold generation for the minimum penetration axis.
	 *
	 * Axes: the polygon face plane, the three box face planes and the
	 * 3 x N box-axis/polygon-edge cross products. The axis with the
	 * smallest escape distance wins; face axes beat edge axes on near ties
	 * (SAT_CROSS_BIAS) because a clipped face manifold is stable frame to
	 * frame while an edge point manifold is not.
	 *
	 * The mesh is one-sided sheets: the mesh normal points into the solid,
	 * and (like the old vertex code, which always used -meshNormal) no
	 * generated push ever points into that solid side. Non-tangential axes
	 * therefore have their escape direction fixed by the outward normal
	 * instead of freely picking the cheaper side - a naive min-over-both-
	 * sides SAT will quietly pick "through the wall" as the cheaper escape
	 * and shove the box into (or through) the solid.
	 */
	private void collidePolygon(int snx, int sny, int snz) {
		int n = polyCount;

		// outward normal = negated mesh normal, normalized defensively
		int nx = -snx, ny = -sny, nz = -snz;
		int len = norm3(nx, ny, nz);
		if(len == 0) return;
		nx = divQ(nx, len); ny = divQ(ny, len); nz = divQ(nz, len);
		polyNX = nx; polyNY = ny; polyNZ = nz;

		bestSep = Integer.MAX_VALUE;
		bestType = -1;

		// 1) polygon face plane; escape direction is fixed to +outward
		axisSeparation(nx, ny, nz);
		if(satSep < -SAT_AXIS_MARGIN) return;
		bestSep = satSep; bestDX = satDirX; bestDY = satDirY; bestDZ = satDirZ;
		bestType = FEATURE_POLY_FACE; bestI = -1; bestJ = -1;

		// 2) the three box face planes
		for(int i = 0; i < 3; i++) {
			column(i);
			axisSeparation(colBuf[0], colBuf[1], colBuf[2]);
			if(satSep < -SAT_AXIS_MARGIN) return;
			if(satSep < bestSep) {
				bestSep = satSep; bestDX = satDirX; bestDY = satDirY; bestDZ = satDirZ;
				bestType = FEATURE_BOX_FACE; bestI = i;
			}
		}

		// 3) the edge cross axes: box axis x polygon edge
		for(int i = 0; i < 3; i++) {
			column(i);
			int ux = colBuf[0], uy = colBuf[1], uz = colBuf[2];
			for(int j = 0; j < n; j++) {
				int j1 = (j + 1) % n;
				int ex = (polyPts[j1 * 3] - polyPts[j * 3]) << 12;
				int ey = (polyPts[j1 * 3 + 1] - polyPts[j * 3 + 1]) << 12;
				int ez = (polyPts[j1 * 3 + 2] - polyPts[j * 3 + 2]) << 12;
				if(ex == 0 && ey == 0 && ez == 0) continue;
				// cross of two Q12 vectors, result Q12
				long lx = ((long) uy * ez - (long) uz * ey) >> 12;
				long ly = ((long) uz * ex - (long) ux * ez) >> 12;
				long lz = ((long) ux * ey - (long) uy * ex) >> 12;
				long l2 = lx * lx + ly * ly + lz * lz;
				if(l2 <= 0) continue;
				int l = isqrt(l2);
				if(l == 0) continue;
				long e2 = (long) ex * ex + (long) ey * ey + (long) ez * ez;
				// near-parallel pairs: the normalized cross is pure rounding
				// noise. Compare squared (|cross|/|edge| < 1/100) to spare
				// the second isqrt; l2 <= e2 keeps the shift safe.
				if(l2 > e2 / (SAT_PARALLEL_SHIFT * SAT_PARALLEL_SHIFT)) continue;
				int cx = (int) ((lx << 12) / l);
				int cy = (int) ((ly << 12) / l);
				int cz = (int) ((lz << 12) / l);

				axisSeparation(cx, cy, cz);
				if(satSep < -SAT_AXIS_MARGIN) return;
				// face bias: an edge axis must be clearly deeper to win
				if(satSep < bestSep - SAT_CROSS_BIAS) {
					bestSep = satSep; bestDX = cx; bestDY = cy; bestDZ = cz;
					bestType = FEATURE_EDGE; bestI = i; bestJ = j;
				}
			}
		}

		if(bestType == FEATURE_POLY_FACE) emitPolyFaceManifold(n);
		else if(bestType == FEATURE_BOX_FACE) emitBoxFaceManifold(bestI);
		else emitEdgeManifold(n);
	}

	/**
	 * Separation between the box and the current polygon along the Q12 unit
	 * axis (ux,uy,uz): the smaller of the two escape distances, with the
	 * matching escape direction in satDir. Result in satSep (units; < 0 ==
	 * separated gap, > 0 == penetration depth).
	 *
	 * The escape distance is min(d1, d2) over the two sides, NOT the plain
	 * interval overlap: the polygon projects to a single point on its own
	 * face normal (a degenerate interval fully inside the box interval),
	 * where an overlap formula would report ~0 and let a phantom axis win
	 * with a bogus near-perpendicular contact normal.
	 */
	private void axisSeparation(int ux, int uy, int uz) {
		int cx = px >> 12, cy = py >> 12, cz = pz >> 12;
		int base = dotU(cx, cy, cz, ux, uy, uz);
		int rad = boxRadiusAlong(ux, uy, uz);

		int pMin = Integer.MAX_VALUE, pMax = Integer.MIN_VALUE;
		for(int i = 0; i < polyCount; i++) {
			int d = dotU(polyPts[i * 3], polyPts[i * 3 + 1], polyPts[i * 3 + 2], ux, uy, uz);
			if(d < pMin) pMin = d;
			if(d > pMax) pMax = d;
		}

		int d1 = base + rad - pMin;    // escape cost pushing along -axis
		int d2 = pMax - (base - rad);  // escape cost pushing along +axis

		// one-sided sheets: escape pushes may not point into the solid
		int w = mul(ux, polyNX) + mul(uy, polyNY) + mul(uz, polyNZ);
		if(w >= SAT_TANGENTIAL) {
			satSep = d2; satDirX = ux; satDirY = uy; satDirZ = uz;
		} else if(w <= -SAT_TANGENTIAL) {
			satSep = d1; satDirX = -ux; satDirY = -uy; satDirZ = -uz;
		} else if(d1 <= d2) {
			satSep = d1; satDirX = -ux; satDirY = -uy; satDirZ = -uz;
		} else {
			satSep = d2; satDirX = ux; satDirY = uy; satDirZ = uz;
		}
	}

	/** Box projection radius along the Q12 unit axis (ux,uy,uz), units. */
	private int boxRadiusAlong(int ux, int uy, int uz) {
		int r0 = abs(mul(r[0], ux) + mul(r[3], uy) + mul(r[6], uz));
		int r1 = abs(mul(r[1], ux) + mul(r[4], uy) + mul(r[7], uz));
		int r2 = abs(mul(r[2], ux) + mul(r[5], uy) + mul(r[8], uz));
		return mulU(r0, hx >> 12) + mulU(r1, hy >> 12) + mulU(r2, hz >> 12);
	}

	/**
	 * Manifold for a polygon face reference: the box face nearest the
	 * polygon plane (the face actually touching the sheet) is clipped
	 * against the polygon's side planes; every clipped point still within
	 * the touch band of the plane becomes a contact on the polygon plane.
	 */
	private void emitPolyFaceManifold(int n) {
		int dx = bestDX, dy = bestDY, dz = bestDZ;

		// incident box face: axis most aligned with the reference normal,
		// then whichever of its two faces sits closer to the sheet. "Most
		// anti-parallel" (the convex-solid rule) is wrong for one-sided
		// sheets: a box that slid edgewise half across a wall plane would
		// pick its far face as "deepest" and report a bogus deep manifold.
		int d0 = mul(r[0], dx) + mul(r[3], dy) + mul(r[6], dz);
		int d1 = mul(r[1], dx) + mul(r[4], dy) + mul(r[7], dz);
		int d2 = mul(r[2], dx) + mul(r[5], dy) + mul(r[8], dz);
		int fi = 0, fd = d0;
		if(abs(d1) > abs(fd)) { fi = 1; fd = d1; }
		if(abs(d2) > abs(fd)) { fi = 2; fd = d2; }

		int cx = px >> 12, cy = py >> 12, cz = pz >> 12;
		int base = dotU(cx - polyPts[0], cy - polyPts[1], cz - polyPts[2], dx, dy, dz);
		int off = mulU(fd, halfOf(fi));
		// face offsets relative to the box center along the reference normal
		int sdPlus = base + off, sdMinus = base - off;
		int sm;
		if(abs(sdPlus) <= abs(sdMinus)) {
			sm = F;   // face center on the +fi column side
		} else {
			sm = -F;  // face center on the -fi column side
		}

		column(fi);
		int ex = mulU(sm, halfOf(fi));
		int fcx = cx + mulU(ex, colBuf[0]);
		int fcy = cy + mulU(ex, colBuf[1]);
		int fcz = cz + mulU(ex, colBuf[2]);
		int k = (fi + 1) % 3, l = (fi + 2) % 3;
		column(k);
		int hk = halfOf(k);
		int axk = mulU(hk, colBuf[0]), ayk = mulU(hk, colBuf[1]), azk = mulU(hk, colBuf[2]);
		column(l);
		int hl = halfOf(l);
		int axl = mulU(hl, colBuf[0]), ayl = mulU(hl, colBuf[1]), azl = mulU(hl, colBuf[2]);

		// the four corners of the incident face (convex loop order)
		clipA[0] = fcx - axk - axl; clipA[1] = fcy - ayk - ayl; clipA[2] = fcz - azk - azl;
		clipA[3] = fcx + axk - axl; clipA[4] = fcy + ayk - ayl; clipA[5] = fcz + azk - azl;
		clipA[6] = fcx + axk + axl; clipA[7] = fcy + ayk + ayl; clipA[8] = fcz + azk + azl;
		clipA[9] = fcx - axk + axl; clipA[10] = fcy - ayk + ayl; clipA[11] = fcz - azk + azl;
		int m = 4;

		// clip the face against the side planes of the polygon
		int gx = 0, gy = 0, gz = 0;
		for(int i = 0; i < n; i++) {
			gx += polyPts[i * 3]; gy += polyPts[i * 3 + 1]; gz += polyPts[i * 3 + 2];
		}
		gx /= n; gy /= n; gz /= n;
		for(int j = 0; j < n && m > 0; j++) {
			int j1 = (j + 1) % n;
			int qx = polyPts[j * 3], qy = polyPts[j * 3 + 1], qz = polyPts[j * 3 + 2];
			int ex2 = (polyPts[j1 * 3] - qx) << 12;
			int ey2 = (polyPts[j1 * 3 + 1] - qy) << 12;
			int ez2 = (polyPts[j1 * 3 + 2] - qz) << 12;
			// plane normal candidate: edge x outward normal (in-plane, perp edge)
			long mxl = ((long) ey2 * dz - (long) ez2 * dy) >> 12;
			long myl = ((long) ez2 * dx - (long) ex2 * dz) >> 12;
			long mzl = ((long) ex2 * dy - (long) ey2 * dx) >> 12;
			long ml2 = mxl * mxl + myl * myl + mzl * mzl;
			if(ml2 <= 0) continue;
			int ml = isqrt(ml2);
			int mx = (int) ((mxl << 12) / ml);
			int my = (int) ((myl << 12) / ml);
			int mz = (int) ((mzl << 12) / ml);
			// orient AWAY from the polygon interior: clipLoop keeps the
			// dot(P - Q, m) <= 0 side, so the outward direction marks the
			// inside of the half space
			if((long) (gx - qx) * mx + (long) (gy - qy) * my + (long) (gz - qz) * mz > 0) {
				mx = -mx; my = -my; mz = -mz;
			}
			m = clipLoop(clipA, m, clipB, qx, qy, qz, mx, my, mz, 0);
			int[] t = clipA; clipA = clipB; clipB = t;
		}
		if(m == 0) return;

		emitClippedFace(m, dx, dy, dz, polyPts[0], polyPts[1], polyPts[2], 0);
	}

	/**
	 * Manifold for a box face reference: the polygon is clipped against the
	 * side planes of the reference box face; every clipped polygon point
	 * within the touch band of the face plane becomes a contact on that
	 * plane. This is the case that covers a mesh edge (column corner,
	 * door jamb) poking into the middle of a box face - the SAT resolves it
	 * to the exact face or edge axis, no sampling heuristics needed.
	 */
	private void emitBoxFaceManifold(int i) {
		int dx = bestDX, dy = bestDY, dz = bestDZ;
		int cx = px >> 12, cy = py >> 12, cz = pz >> 12;

		int m = polyCount;
		System.arraycopy(polyPts, 0, clipA, 0, polyCount * 3);
		m = clipBoxSide(clipA, m, clipB, cx, cy, cz, (i + 1) % 3);
		if(m == 0) return;
		m = clipBoxSide(clipA, m, clipB, cx, cy, cz, (i + 2) % 3);
		if(m == 0) return;

		// reference plane: the box face toward the solid,
		// dot(P - c, dir) == -h_i  =>  sd = dot(P - c, dir) + h_i
		emitClippedFace(m, dx, dy, dz, cx, cy, cz, halfOf(i));
	}

	/** Clips a loop against both side planes of one box axis. Result in src. */
	private int clipBoxSide(int[] src, int m, int[] dst, int cx, int cy, int cz, int axis) {
		column(axis);
		int h = halfOf(axis);
		m = clipLoop(src, m, dst, cx, cy, cz, colBuf[0], colBuf[1], colBuf[2], h);
		if(m == 0) return 0;
		return clipLoop(dst, m, src, cx, cy, cz, -colBuf[0], -colBuf[1], -colBuf[2], h);
	}

	/**
	 * Manifold for an edge reference: the supporting box edge (along the
	 * box axis that built the cross product, pushed to the extreme along
	 * the reference normal) vs the polygon edge that built it. Contact
	 * point is the midpoint of the two closest segment points.
	 */
	private void emitEdgeManifold(int n) {
		int dx = bestDX, dy = bestDY, dz = bestDZ;
		int i = bestI, j = bestJ;
		int cx = px >> 12, cy = py >> 12, cz = pz >> 12;

		// supporting edge of the box: along axis i, extreme along -dir
		int bx = cx, by = cy, bz = cz;
		for(int k = 0; k < 3; k++) {
			if(k == i) continue;
			column(k);
			int d = mul(colBuf[0], dx) + mul(colBuf[1], dy) + mul(colBuf[2], dz);
			int sk = d > 0 ? -F : F;
			int hk = mulU(sk, halfOf(k));
			bx += mulU(hk, colBuf[0]);
			by += mulU(hk, colBuf[1]);
			bz += mulU(hk, colBuf[2]);
		}
		column(i);
		int hI = mulU(F, halfOf(i));
		int e1x = bx - mulU(hI, colBuf[0]);
		int e1y = by - mulU(hI, colBuf[1]);
		int e1z = bz - mulU(hI, colBuf[2]);
		int e2x = bx + mulU(hI, colBuf[0]);
		int e2y = by + mulU(hI, colBuf[1]);
		int e2z = bz + mulU(hI, colBuf[2]);

		int j1 = (j + 1) % n;
		segmentClosest(e1x, e1y, e1z, e2x, e2y, e2z,
				polyPts[j * 3], polyPts[j * 3 + 1], polyPts[j * 3 + 2],
				polyPts[j1 * 3], polyPts[j1 * 3 + 1], polyPts[j1 * 3 + 2]);

		emitPoint((segPx + segQx) >> 1, (segPy + segQy) >> 1, (segPz + segQz) >> 1,
				dx, dy, dz, bestSep);
	}

	/**
	 * Emits the clipped incident points of a face manifold: points within
	 * the touch band of the reference plane (dot(P - ref, dir) + offset)
	 * become contacts projected onto that plane, so the manifold height
	 * never wobbles with the penetration depth. If the band rejects
	 * everything, the single deepest point is emitted anyway - a real
	 * contact must never flicker off for a frame, that is exactly the
	 * alternating-contact jitter.
	 */
	private void emitClippedFace(int m, int dx, int dy, int dz,
			int rx, int ry, int rz, int offset) {
		int kept = 0;
		int minSd = Integer.MAX_VALUE, deepest = 0;
		for(int i = 0; i < m; i++) {
			int wx = clipA[i * 3], wy = clipA[i * 3 + 1], wz = clipA[i * 3 + 2];
			int sd = dotU(wx - rx, wy - ry, wz - rz, dx, dy, dz) + offset;
			sdBuf[i] = sd;
			if(sd < minSd) { minSd = sd; deepest = i; }
			if(sd <= SAT_TOUCH_TOL) kept++;
		}
		if(kept == 0) {
			if(minSd > SAT_AXIS_MARGIN) {
				// Deep straddle: the incident face has crossed the reference
				// plane entirely (fast box vs a thin sheet), so every point
				// is past the touch band and the manifold would come up
				// empty. Dropping the contact hides the penetration from the
				// substep rollback and the box tunnels through. Emit the
				// deepest point with the SAT escape depth instead: deep
				// enough to roll the step back, and if it is ever solved it
				// pushes the box out along the minimum escape axis.
				if(bestSep <= 0) return;
				int wx = clipA[deepest * 3] - mulU(minSd, dx);
				int wy = clipA[deepest * 3 + 1] - mulU(minSd, dy);
				int wz = clipA[deepest * 3 + 2] - mulU(minSd, dz);
				emitPoint(wx << 12, wy << 12, wz << 12, dx, dy, dz, bestSep << 12);
				return;
			}
			// No point in the resting band yet: this is the speculative
			// pre-touch pass. Emit every point inside the approach band, NOT
			// just the deepest one - a flat face must land as a full uniform
			// manifold, otherwise the whole impact impulse hits one corner
			// and its torque starts the box tumbling on a flat floor.
			for(int i = 0; i < m; i++) if(sdBuf[i] <= SAT_AXIS_MARGIN) kept++;
			if(kept > MAX_MANIFOLD_POINTS) kept = MAX_MANIFOLD_POINTS;
			// compact to the in-band points (they are all spec contacts,
			// keep them spread instead of deepest-first)
			int c = 0;
			for(int i = 0; i < m && c < kept; i++) {
				if(sdBuf[i] > SAT_AXIS_MARGIN) continue;
				if(c != i) {
					clipA[c * 3] = clipA[i * 3];
					clipA[c * 3 + 1] = clipA[i * 3 + 1];
					clipA[c * 3 + 2] = clipA[i * 3 + 2];
					sdBuf[c] = sdBuf[i];
				}
				c++;
			}
			kept = c;
			for(int i = 0; i < kept; i++) {
				int sd = sdBuf[i];
				int wx = clipA[i * 3] - mulU(sd, dx);
				int wy = clipA[i * 3 + 1] - mulU(sd, dy);
				int wz = clipA[i * 3 + 2] - mulU(sd, dz);
				emitPoint(wx << 12, wy << 12, wz << 12, dx, dy, dz, (-sd) << 12);
			}
			return;
		}
		kept = selectSpread(m);
		for(int i = 0; i < kept; i++) {
			int sd = sdBuf[i];
			int wx = clipA[i * 3] - mulU(sd, dx);
			int wy = clipA[i * 3 + 1] - mulU(sd, dy);
			int wz = clipA[i * 3 + 2] - mulU(sd, dz);
			emitPoint(wx << 12, wy << 12, wz << 12, dx, dy, dz, (-sd) << 12);
		}
	}

	/**
	 * Compacts the in-band manifold points (sd <= SAT_TOUCH_TOL) to the
	 * front of clipA/sdBuf and caps them to MAX_MANIFOLD_POINTS: deepest
	 * point first, then greedy farthest-point spread so the retained
	 * points still span the contact area (and its torque) honestly.
	 * Compaction always runs - the in-band points are generally NOT a
	 * prefix of the clipped loop, and the caller emits indices 0..count-1.
	 */
	private int selectSpread(int m) {
		int c = 0;
		for(int i = 0; i < m; i++) {
			if(sdBuf[i] > SAT_TOUCH_TOL) continue;
			if(c != i) {
				clipA[c * 3] = clipA[i * 3];
				clipA[c * 3 + 1] = clipA[i * 3 + 1];
				clipA[c * 3 + 2] = clipA[i * 3 + 2];
				sdBuf[c] = sdBuf[i];
			}
			c++;
		}
		m = c;
		if(m <= MAX_MANIFOLD_POINTS) return m;
		int sel = 0;
		int seed = 0, best = Integer.MAX_VALUE;
		for(int i = 0; i < m; i++) if(sdBuf[i] < best) { best = sdBuf[i]; seed = i; }
		selIdx[sel++] = seed;
		while(sel < MAX_MANIFOLD_POINTS) {
			int far = -1;
			long farD = -1;
			for(int i = 0; i < m; i++) {
				boolean used = false;
				for(int s = 0; s < sel; s++) if(selIdx[s] == i) { used = true; break; }
				if(used) continue;
				long dmin = Long.MAX_VALUE;
				for(int s = 0; s < sel; s++) {
					int o = selIdx[s];
					long ddx = clipA[i * 3] - clipA[o * 3];
					long ddy = clipA[i * 3 + 1] - clipA[o * 3 + 1];
					long ddz = clipA[i * 3 + 2] - clipA[o * 3 + 2];
					long d2 = ddx * ddx + ddy * ddy + ddz * ddz;
					if(d2 < dmin) dmin = d2;
				}
				if(dmin > farD) { farD = dmin; far = i; }
			}
			if(far < 0) break;
			selIdx[sel++] = far;
		}
		// snapshot then compact (source and target indices may overlap)
		for(int s = 0; s < sel; s++) {
			int o = selIdx[s];
			selTmp[s * 3] = clipA[o * 3];
			selTmp[s * 3 + 1] = clipA[o * 3 + 1];
			selTmp[s * 3 + 2] = clipA[o * 3 + 2];
			selSdTmp[s] = sdBuf[o];
		}
		for(int s = 0; s < sel; s++) {
			clipA[s * 3] = selTmp[s * 3];
			clipA[s * 3 + 1] = selTmp[s * 3 + 1];
			clipA[s * 3 + 2] = selTmp[s * 3 + 2];
			sdBuf[s] = selSdTmp[s];
		}
		return sel;
	}

	/**
	 * Adds one manifold point (Q12 position, Q12 unit normal, Q12 pen)
	 * with cross-polygon deduplication: adjacent coplanar polygons (a wall
	 * or floor built from several triangles) each generate their own
	 * manifold, and the shared seam produces the same contact twice.
	 * Double impulses at one spot over-correct and snap the box - the
	 * duplicate is merged into the deeper of the two instead.
	 */
	private void emitPoint(int x, int y, int z, int nx, int ny, int nz, int pen) {
		for(int i = 0; i < numContacts; i++) {
			if(mul(nx, cnx[i]) + mul(ny, cny[i]) + mul(nz, cnz[i]) < MERGE_NORMAL_DOT) continue;
			long ex = (long) x - cpx[i], ey = (long) y - cpy[i], ez = (long) z - cpz[i];
			if(ex * ex + ey * ey + ez * ez > MERGE_DIST2) continue;
			if(pen > cpen[i]) {
				cpx[i] = x; cpy[i] = y; cpz[i] = z;
				cpen[i] = pen;
				if(pen > maxPenetration) maxPenetration = pen;
			}
			return;
		}
		addContact(x, y, z, nx, ny, nz, pen);
	}

	private void addContact(int x, int y, int z, int nx, int ny, int nz, int pen) {
		if(numContacts >= MAX_CONTACTS) return;
		cpx[numContacts] = x; cpy[numContacts] = y; cpz[numContacts] = z;
		cnx[numContacts] = nx; cny[numContacts] = ny; cnz[numContacts] = nz;
		cpen[numContacts] = pen;
		if(pen > maxPenetration) maxPenetration = pen;
		// outward normal pointing mostly up == supported by the ground
		if(ny > (F * 7 / 10)) groundContact = true;
		++numContacts;
	}

	// ===================== impulses =====================

	private final int[] accN = new int[MAX_CONTACTS];
	private final int[] accT = new int[MAX_CONTACTS];
	private final int[] vbias = new int[MAX_CONTACTS];

	private void applyImpulses() {
		for(int i = 0; i < numContacts; i++) {
			accN[i] = 0; accT[i] = 0; vbias[i] = 0;
		}

		// Sequential impulses with accumulated magnitudes: several Gauss-Seidel
		// sweeps let a multi-point face contact converge; without them a resting
		// box gets four independent impulses and tumbles/jitters.
		// Prepass: restitution targets are fixed once from the approach
		// velocities before any impulse is applied, otherwise targets
		// computed mid-sweep are mutually inconsistent across contacts.
		for(int i = 0; i < numContacts; i++) {
			int rx = cpx[i] - px, ry = cpy[i] - py, rz = cpz[i] - pz;
			int crx = mul(wy, rz) - mul(wz, ry);
			int cry = mul(wz, rx) - mul(wx, rz);
			int crz = mul(wx, ry) - mul(wy, rx);
			int vn = mul(vx + crx, cnx[i]) + mul(vy + cry, cny[i])
					+ mul(vz + crz, cnz[i]);
			vbias[i] = -vn > RESTITUTION_SPEED ? -mul(RESTITUTION, vn) : 0;
		}

		for(int iter = 0; iter < IMPULSE_ITERATIONS; iter++) {
			for(int i = 0; i < numContacts; i++) {
				int rx = cpx[i] - px, ry = cpy[i] - py, rz = cpz[i] - pz;
				int nx = cnx[i], ny = cny[i], nz = cnz[i];

				// relative velocity at the contact point: v + w x r
				int crx = mul(wy, rz) - mul(wz, ry);
				int cry = mul(wz, rx) - mul(wx, rz);
				int crz = mul(wx, ry) - mul(wy, rx);
				int rvx = vx + crx, rvy = vy + cry, rvz = vz + crz;
				int vn = mul(rvx, nx) + mul(rvy, ny) + mul(rvz, nz);

				// K_n = 1/m + ((I^-1 (r x n)) x r) . n
				int rnx = mul(ry, nz) - mul(rz, ny);
				int rny = mul(rz, nx) - mul(rx, nz);
				int rnz = mul(rx, ny) - mul(ry, nx);
				int irx = eval24X(invIWorld, rnx, rny, rnz);
				int iry = eval24Y(invIWorld, rnx, rny, rnz);
				int irz = eval24Z(invIWorld, rnx, rny, rnz);
				int krx = mul(iry, rz) - mul(irz, ry);
				int kry = mul(irz, rx) - mul(irx, rz);
				int krz = mul(irx, ry) - mul(iry, rx);
				int kn = invMass + mul(krx, nx) + mul(kry, ny) + mul(krz, nz);

				// Normal impulse; the restitution target comes from the
				// prepass and is enforced by every sweep so later sweeps do
				// not eat the bounce.
				if(kn > 0) {
					int dN = divQ(vbias[i] - vn, kn);
					int newAcc = accN[i] + dN;
					if(newAcc < 0) newAcc = 0;
					dN = newAcc - accN[i];
					accN[i] = newAcc;
					if(dN != 0) {
						int imp = mul(dN, invMass);
						vx += mul(nx, imp);
						vy += mul(ny, imp);
						vz += mul(nz, imp);
						lx += mul(ry, mul(nz, dN)) - mul(rz, mul(ny, dN));
						ly += mul(rz, mul(nx, dN)) - mul(rx, mul(nz, dN));
						lz += mul(rx, mul(ny, dN)) - mul(ry, mul(nx, dN));
						wx = eval24X(invIWorld, lx, ly, lz);
						wy = eval24Y(invIWorld, lx, ly, lz);
						wz = eval24Z(invIWorld, lx, ly, lz);
					}
				}

				if(accN[i] <= 0) continue;

				// Friction: tangent relative velocity, Coulomb clamp mu * jn
				crx = mul(wy, rz) - mul(wz, ry);
				cry = mul(wz, rx) - mul(wx, rz);
				crz = mul(wx, ry) - mul(wy, rx);
				rvx = vx + crx; rvy = vy + cry; rvz = vz + crz;
				int vnn = mul(rvx, nx) + mul(rvy, ny) + mul(rvz, nz);
				int tx = rvx - mul(nx, vnn);
				int ty = rvy - mul(ny, vnn);
				int tz = rvz - mul(nz, vnn);
				int tl = norm3(tx, ty, tz);
				if(tl >= 1) {
					tx = divQ(tx, tl); ty = divQ(ty, tl); tz = divQ(tz, tl);

					int rtx = mul(ry, tz) - mul(rz, ty);
					int rty = mul(rz, tx) - mul(rx, tz);
					int rtz = mul(rx, ty) - mul(ry, tx);
					int itx = eval24X(invIWorld, rtx, rty, rtz);
					int ity = eval24Y(invIWorld, rtx, rty, rtz);
					int itz = eval24Z(invIWorld, rtx, rty, rtz);
					int ktx = mul(ity, rz) - mul(itz, ry);
					int kty = mul(itz, rx) - mul(itx, rz);
					int ktz = mul(itx, ry) - mul(ity, rx);
					int kt = invMass + mul(ktx, tx) + mul(kty, ty) + mul(ktz, tz);

					int vt = mul(rvx, tx) + mul(rvy, ty) + mul(rvz, tz);
					if(kt > 0) {
						int dT = -divQ(vt, kt);
						int maxFric = abs(mul(FRICTION, accN[i]));
						int newAcc = accT[i] + dT;
						if(newAcc > maxFric) newAcc = maxFric;
						else if(newAcc < -maxFric) newAcc = -maxFric;
						dT = newAcc - accT[i];
						accT[i] = newAcc;
						if(dT != 0) {
							int imp = mul(dT, invMass);
							vx += mul(tx, imp);
							vy += mul(ty, imp);
							vz += mul(tz, imp);
							lx += mul(ry, mul(tz, dT)) - mul(rz, mul(ty, dT));
							ly += mul(rz, mul(tx, dT)) - mul(rx, mul(tz, dT));
							lz += mul(rx, mul(ty, dT)) - mul(ry, mul(tx, dT));
							wx = eval24X(invIWorld, lx, ly, lz);
							wy = eval24Y(invIWorld, lx, ly, lz);
							wz = eval24Z(invIWorld, lx, ly, lz);
						}
					}
				}
			}
		}

		// De-penetration runs as its own position-only pass.
		correctPositions();
	}

	/**
	 * Sequential position projection over every contact. Each iteration
	 * moves the center and rotates the body just like the velocity impulses
	 * do, but touches positions only, so it never injects momentum. Splitting
	 * the correction across all contacts (instead of one big snap on the
	 * deepest point) prevents the corner-jam energy pump.
	 */
	private void correctPositions() {
		final int beta = (int) ((long) F / POSITION_ITERATIONS);
		for(int iter = 0; iter < POSITION_ITERATIONS; iter++) {
			for(int i = 0; i < numContacts; i++) {
				int pen = cpen[i];
				if(pen <= POSITION_SLOP << 12) continue;
				int rx = cpx[i] - px, ry = cpy[i] - py, rz = cpz[i] - pz;
				int nx = cnx[i], ny = cny[i], nz = cnz[i];

				int rnx = mul(ry, nz) - mul(rz, ny);
				int rny = mul(rz, nx) - mul(rx, nz);
				int rnz = mul(rx, ny) - mul(ry, nx);
				int irx = eval24X(invIWorld, rnx, rny, rnz);
				int iry = eval24Y(invIWorld, rnx, rny, rnz);
				int irz = eval24Z(invIWorld, rnx, rny, rnz);
				int krx = mul(iry, rz) - mul(irz, ry);
				int kry = mul(irz, rx) - mul(irx, rz);
				int krz = mul(irx, ry) - mul(iry, rx);
				int k = invMass + mul(krx, nx) + mul(kry, ny) + mul(krz, nz);
				if(k <= 0) continue;

				int target = mul(pen - (POSITION_SLOP << 12), beta);
				int dp = divQ(target, k);
				px += mul(nx, mul(dp, invMass));
				py += mul(ny, mul(dp, invMass));
				pz += mul(nz, mul(dp, invMass));

				// angular position step dq = I^-1 (r x n * dp)
				int qx = eval24X(invIWorld,
						mul(ry, mul(nz, dp)) - mul(rz, mul(ny, dp)),
						mul(rz, mul(nx, dp)) - mul(rx, mul(nz, dp)),
						mul(rx, mul(ny, dp)) - mul(ry, mul(nx, dp)));
				int qy = eval24Y(invIWorld,
						mul(ry, mul(nz, dp)) - mul(rz, mul(ny, dp)),
						mul(rz, mul(nx, dp)) - mul(rx, mul(nz, dp)),
						mul(rx, mul(ny, dp)) - mul(ry, mul(nx, dp)));
				int qz = eval24Z(invIWorld,
						mul(ry, mul(nz, dp)) - mul(rz, mul(ny, dp)),
						mul(rz, mul(nx, dp)) - mul(rx, mul(nz, dp)),
						mul(rx, mul(ny, dp)) - mul(ry, mul(nx, dp)));
				rotateMatrix(qx, qy, qz);
				recomputeWorldInertia();
			}
		}
		fixMatrix();
		recomputeWorldInertia();
	}

	/** R += skew(q) * R in place (same first order update as integration). */
	private void rotateMatrix(int qx, int qy, int qz) {
		for(int row = 0; row < 3; row++) {
			int s0, s1, s2;
			if(row == 0) { s0 = 0; s1 = -qz; s2 = qy; }
			else if(row == 1) { s0 = qz; s1 = 0; s2 = -qx; }
			else { s0 = -qy; s1 = qx; s2 = 0; }
			for(int col = 0; col < 3; col++) {
				int v = mul(s0, r[col]) + mul(s1, r[3 + col]) + mul(s2, r[6 + col]);
				r[row * 3 + col] += v;
			}
		}
	}

	private void clampVelocity() {
		if(vx > MAX_LINEAR) vx = MAX_LINEAR; else if(vx < -MAX_LINEAR) vx = -MAX_LINEAR;
		if(vy > MAX_LINEAR) vy = MAX_LINEAR; else if(vy < -MAX_LINEAR) vy = -MAX_LINEAR;
		if(vz > MAX_LINEAR) vz = MAX_LINEAR; else if(vz < -MAX_LINEAR) vz = -MAX_LINEAR;
		if(wx > MAX_ANGULAR) wx = MAX_ANGULAR; else if(wx < -MAX_ANGULAR) wx = -MAX_ANGULAR;
		if(wy > MAX_ANGULAR) wy = MAX_ANGULAR; else if(wy < -MAX_ANGULAR) wy = -MAX_ANGULAR;
		if(wz > MAX_ANGULAR) wz = MAX_ANGULAR; else if(wz < -MAX_ANGULAR) wz = -MAX_ANGULAR;
		// momentum must stay consistent with the clamped velocities
		recomputeMomentum();
	}

	// ===================== vertices / AABB =====================

	/** Recomputes the world AABB and the center-to-corner reach. */
	private void computeVertices() {
		// axis columns
		int c0x = r[0], c0y = r[3], c0z = r[6];
		int c1x = r[1], c1y = r[4], c1z = r[7];
		int c2x = r[2], c2y = r[5], c2z = r[8];
		int ex = hx, ey = hy, ez = hz;

		int mnx = Integer.MAX_VALUE, mny = Integer.MAX_VALUE, mnz = Integer.MAX_VALUE;
		int mxx = Integer.MIN_VALUE, mxy = Integer.MIN_VALUE, mxz = Integer.MIN_VALUE;

		// 0:--- 1:+-- 2:+-+ 3:--+ 4:-++ 5:-+- 6:++- 7:+++
		for(int k = 0; k < VERTICES; k++) {
			int sx = (k == 1 || k == 2 || k == 6 || k == 7) ? 1 : -1;
			int sy = (k == 4 || k == 5 || k == 6 || k == 7) ? 1 : -1;
			int sz = (k == 2 || k == 3 || k == 4 || k == 7) ? 1 : -1;
			int ux = (px + sx * mul(c0x, ex) + sy * mul(c1x, ey) + sz * mul(c2x, ez)) >> 12;
			int uy = (py + sx * mul(c0y, ex) + sy * mul(c1y, ey) + sz * mul(c2y, ez)) >> 12;
			int uz = (pz + sx * mul(c0z, ex) + sy * mul(c1z, ey) + sz * mul(c2z, ez)) >> 12;
			if(ux < mnx) mnx = ux; if(ux > mxx) mxx = ux;
			if(uy < mny) mny = uy; if(uy > mxy) mxy = uy;
			if(uz < mnz) mnz = uz; if(uz > mxz) mxz = uz;
		}
		boxMinX = mnx; boxMinY = mny; boxMinZ = mnz;
		boxMaxX = mxx; boxMaxY = mxy; boxMaxZ = mxz;

		// largest center-to-corner reach, used by the broadphase band
		int rxr = abs(c0x) * (ex >> 12) + abs(c1x) * (ey >> 12) + abs(c2x) * (ez >> 12);
		int ryr = abs(c0y) * (ex >> 12) + abs(c1y) * (ey >> 12) + abs(c2y) * (ez >> 12);
		int rzr = abs(c0z) * (ex >> 12) + abs(c1z) * (ey >> 12) + abs(c2z) * (ez >> 12);
		int cr = (rxr >> 12); if((ryr >> 12) > cr) cr = ryr >> 12; if((rzr >> 12) > cr) cr = rzr >> 12;
		cornerRadius = cr;
	}

	// ===================== rollback =====================

	private void backup() {
		bpx = px; bpy = py; bpz = pz;
		bvx = vx; bvy = vy; bvz = vz;
		blx = lx; bly = ly; blz = lz;
		bwx = wx; bwy = wy; bwz = wz;
		System.arraycopy(r, 0, br, 0, 9);
		System.arraycopy(invIWorld, 0, biw, 0, 9);
	}

	private void restore() {
		px = bpx; py = bpy; pz = bpz;
		vx = bvx; vy = bvy; vz = bvz;
		lx = blx; ly = bly; lz = blz;
		wx = bwx; wy = bwy; wz = bwz;
		System.arraycopy(br, 0, r, 0, 9);
		System.arraycopy(biw, 0, invIWorld, 0, 9);
	}

	// ===================== static math =====================

	/** Q12 multiply (arithmetic shift, matches the C fixed point code). */
	public static int mul(int a, int b) {
		return (int) ((long) a * b >> 12);
	}

	/** Q12 division: a / b with both values Q12, result Q12. */
	public static int divQ(int a, int b) {
		return (int) (((long) a << 12) / b);
	}

	/** Q12 (scaled) * units -> units. */
	private static int mulU(int q, int units) {
		return (int) (((long) q * units) >> 12);
	}

	/** units dot Q12 direction -> units. */
	private static int dotU(int x, int y, int z, int ux, int uy, int uz) {
		return (int) (((long) x * ux + (long) y * uy + (long) z * uz) >> 12);
	}

	private static int evalX(int[] m, int x, int y, int z) {
		return mul(m[0], x) + mul(m[1], y) + mul(m[2], z);
	}
	private static int evalY(int[] m, int x, int y, int z) {
		return mul(m[3], x) + mul(m[4], y) + mul(m[5], z);
	}
	private static int evalZ(int[] m, int x, int y, int z) {
		return mul(m[6], x) + mul(m[7], y) + mul(m[8], z);
	}

	private static void identity3(int[] m) {
		m[0] = F; m[1] = 0; m[2] = 0;
		m[3] = 0; m[4] = F; m[5] = 0;
		m[6] = 0; m[7] = 0; m[8] = F;
	}

	private final int[] tmpMatrix = new int[9];

	/** Q12 magnitude of a Q12 vector. */
	private static int norm3(int x, int y, int z) {
		return isqrt((long) x * x + (long) y * y + (long) z * z);
	}

	/** Integer square root (plain integer domain, floor). */
	public static int isqrt(long x) {
		if(x <= 0) return 0;
		long rem = 0, root = 0;
		for(int i = 31; i >= 0; i--) {
			rem = (rem << 2) | ((x >>> (i * 2)) & 3);
			long t = (root << 2) | 1;
			if(rem >= t) { rem -= t; root = (root << 1) | 1; }
			else root <<= 1;
		}
		return (int) root;
	}

	private static int abs(int v) { return v < 0 ? -v : v; }

	/** Reads orientation column i into colBuf (Q12). */
	private void column(int i) {
		colBuf[0] = r[i]; colBuf[1] = r[3 + i]; colBuf[2] = r[6 + i];
	}

	/** Half extent of axis i, engine units. */
	private int halfOf(int i) {
		return (i == 0 ? hx : i == 1 ? hy : hz) >> 12;
	}

	// ===================== geometry helpers =====================

	/**
	 * Sutherland-Hodgman clip of a convex point loop (engine units, up to
	 * 8 points) against the half space dot(P - Q, N) <= keep (N is Q12,
	 * keep in units). Result into dst, point count returned.
	 */
	private static int clipLoop(int[] src, int n, int[] dst,
			int qx, int qy, int qz, int nx, int ny, int nz, int keep) {
		int count = 0;
		long k = (long) keep << 12;
		for(int i = 0; i < n; i++) {
			int i2 = (i + 1) % n;
			int sx = src[i * 3], sy = src[i * 3 + 1], sz = src[i * 3 + 2];
			int ex = src[i2 * 3], ey = src[i2 * 3 + 1], ez = src[i2 * 3 + 2];
			long fs = (long) (sx - qx) * nx + (long) (sy - qy) * ny + (long) (sz - qz) * nz;
			long fe = (long) (ex - qx) * nx + (long) (ey - qy) * ny + (long) (ez - qz) * nz;
			boolean sIn = fs <= k, eIn = fe <= k;
			if(sIn) {
				if(count < 8) {
					dst[count * 3] = sx; dst[count * 3 + 1] = sy; dst[count * 3 + 2] = sz;
					count++;
				}
			}
			if(sIn != eIn) {
				if(count < 8) {
					long t14 = (fs - k) * 16384 / (fs - fe);
					dst[count * 3] = sx + (int) (((long) (ex - sx) * t14) >> 14);
					dst[count * 3 + 1] = sy + (int) (((long) (ey - sy) * t14) >> 14);
					dst[count * 3 + 2] = sz + (int) (((long) (ez - sz) * t14) >> 14);
					count++;
				}
			}
		}
		return count;
	}

	/**
	 * Closest points between two segments (all coordinates engine units).
	 * Directions are normalized to Q12 first, which keeps every product
	 * comfortably inside long/int range; the two stage clamp is the classic
	 * Ericson "closest point of two segments" with the degenerate parallel
	 * branch handled by projecting onto the longer segment.
	 */
	private void segmentClosest(int ax, int ay, int az, int bx, int by, int bz,
			int cx, int cy, int cz, int dx, int dy, int dz) {
		int d1x = bx - ax, d1y = by - ay, d1z = bz - az;
		int d2x = dx - cx, d2y = dy - cy, d2z = dz - cz;
		int l1 = norm3(d1x, d1y, d1z);
		int l2 = norm3(d2x, d2y, d2z);
		if(l1 == 0 || l2 == 0) {
			// degenerate (zero) edge: fall back to the segment midpoints
			segPx = (ax + bx) >> 1; segPy = (ay + by) >> 1; segPz = (az + bz) >> 1;
			segQx = (cx + dx) >> 1; segQy = (cy + dy) >> 1; segQz = (cz + dz) >> 1;
			return;
		}
		int u1x = divQ(d1x, l1), u1y = divQ(d1y, l1), u1z = divQ(d1z, l1);
		int u2x = divQ(d2x, l2), u2y = divQ(d2y, l2), u2z = divQ(d2z, l2);
		int rx = ax - cx, ry = ay - cy, rz = az - cz;
		int b = mul(u1x, u2x) + mul(u1y, u2y) + mul(u1z, u2z);
		int c = dotU(rx, ry, rz, u1x, u1y, u1z);
		int f = dotU(rx, ry, rz, u2x, u2y, u2z);
		int denom = F - mul(b, b);
		int s, t;
		if(denom < F / 64) {
			// near-parallel: project onto the longer segment, clamp, re-project
			if(l1 >= l2) {
				s = clampI(-c, 0, l1);
				t = clampI(mul(b, s) - f, 0, l2);
			} else {
				t = clampI(-f, 0, l2);
				s = clampI(mul(b, t) - c, 0, l1);
			}
		} else {
			// s = -(b*f + c) / (1 - b^2), then t from s, then s from t
			s = clampI(divQ(-(mul(b, f) + c), denom), 0, l1);
			t = clampI(mul(b, s) - f, 0, l2);
			s = clampI(mul(b, t) - c, 0, l1);
		}
		segPx = ax + mulU(u1x, s); segPy = ay + mulU(u1y, s); segPz = az + mulU(u1z, s);
		segQx = cx + mulU(u2x, t); segQy = cy + mulU(u2y, t); segQz = cz + mulU(u2z, t);
	}

	private static int clampI(int v, int lo, int hi) {
		return v < lo ? lo : v > hi ? hi : v;
	}
}
